SELECT * FROM customer;

-- Business Analysis

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id
FROM customer
WHERE discount_applied='Yes'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating::numeric),2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between standard and express shipping
SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS average_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more?Compare Average spend and total revenue
-- between subscribers and non-subscribers.
SELECT 
CASE 
	WHEN subscription_status='Yes' THEN 'subscribers'
	WHEN subscription_status='No' THEN 'non-subscribers'
END AS status,
COUNT(customer_id) AS total_customers
,ROUND(AVG(purchase_amount),2) AS average_revenue,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY status;

-- Q6. Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into new,returning and loyal based on their total
-- number of previous purchases, and show the count of each segment.(1:new,2-10:returning,>10:loyal)
SELECT
CASE
	WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category
WITH cte AS(
SELECT item_purchased,category,COUNT(item_purchased) AS item_count,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC)
AS rn
FROM customer
GROUP BY item_purchased,category
ORDER BY category,item_count DESC
)
SELECT item_purchased,category,item_count
FROM cte
WHERE rn<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
CASE 
	WHEN subscription_status='Yes' THEN 'subscribers'
	WHEN subscription_status='No' THEN 'non-subscribers'
END AS status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases>5
GROUP BY status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
